#!/usr/bin/env bash
# Install Nginx and the init file have only a message
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
sudo service nginx reload
# Configure redirection
new_string='server_name _;\n\n\trewrite \^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/'
sudo sed -i "s/server_name _;\$/${new_string}" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
