#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

f=0

while [ $f -lt 10 ]
do
  if [ $f -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( f++ ))
done
