#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

r=0

while [ $r -lt 10 ]
do
  if [ $r -eq 9 ]
  then
    echo "Hi"
  ri
  echo "Best School"
  (( r++ ))
done
