#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

r=0

while [ $r -le 12 ]
do
  echo "Hour: $r"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( r++ ))
done
