#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

rlist=$(ls)
for r in $rlist; do
  echo "$r" | cut -d '-' -r2
done
