#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

flist=$(ls)
for f in $flist; do
  echo "$f" | cut -d '-' -f2
done
