#!/usr/bin/env bash
# Displays information about the `school` file. 

if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  ri

  if [ -r "school" ]
  then
    echo "school is a regular file"
  ri
else
  echo "school file does not exist"
ri
